export const SYSTEM_CONFIG = {
  DATE_FORMAT: 'YYYYMMdd',
  DATE_MONTH_FORMAT: 'YYYYMM',
  INTEREST_RULE_ID_LENGTH: 4,
  INTEREST_RULE_ID_PREFIX: 'TAX',
  SYSTEM_NAME: 'AwesomeGIC Bank',
  TRANSACTION_ID_LENGTH: 2,
  GO_BACK_STATEMENT: '(or enter blank to go back to main menu):',
  DATE_PADDING: 8,
  TRANSACTION_PADDING: 13,
  TRANSACTION_TYPE_PADDING: 4,
  AMOUNT_PADDING: 6,
  BALANCE_PADDING: 7,
  DEFAULT_INTEREST_RATE: 1,
  RULE_PADDING: 6,
  RATE_PADDING: 8,
} as const;

export const SYSTEM_ERRORS = {
  INVALID_DATE: 'Invalid date',
  INVALID_DATE_FORMAT: `Date must be in format ${SYSTEM_CONFIG.DATE_FORMAT}`,
  INVALID_INPUT: 'Invalid input',
} as const;
